# Generated by Django 3.0.2 on 2020-01-20 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comunicados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=50, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=50, null=True)),
                ('documento', models.FileField(blank=True, null=True, upload_to='doc_comunicados/')),
                ('imagen', models.ImageField(upload_to='img_comunicados', verbose_name='Imagen')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('link', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
