# Generated by Django 3.0.2 on 2020-01-21 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_comunicados_usuarios'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuarios',
            options={},
        ),
    ]
