# Generated by Django 3.0.2 on 2020-01-21 10:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0004_auto_20200121_0357'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comunicados',
            name='usuarios',
        ),
        migrations.CreateModel(
            name='Mi_comunicado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comunicado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Comunicados')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
