# Generated by Django 3.0.2 on 2020-01-21 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20200121_0432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mi_comunicado',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Usuarios'),
        ),
    ]
