# Generated by Django 3.0 on 2020-01-21 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20200121_0434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comunicados',
            name='descripcion',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='comunicados',
            name='titulo',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
    ]
